### ISSUE TITLE
current release is broken, new release?

### ISSUE THREAD

**Issue by dadiletta** [maxcountryman/flask-uploads#33]
Past werkzeug v0.16.1 we get the following error:
```
 File "/Projects/flaskinni/venv/lib/python3.7/site-packages/flask_uploads.py", line 26, in <module>
from werkzeug import secure_filename, FileStorage
ImportError: cannot import name 'secure_filename' from 'werkzeug''
```
It appears the fix has already been made. Can it be deployed to pypi?

**Comment by lennymd** [comment]
What was the fix? I tried installing this package with pip from github but this error persists.

**Comment by dadiletta** [comment]
You have to stick with Python 3.7 until they publish the existing GitHub repo that has the fixed reference to pypi. I'm about 80% sure I'm understanding the situation correctly.

**Comment by BigCheeze45** [comment]
Encounter same issue. Was able to resolve it by importing Flask_Uploads *after* (see below) my Flask app was created. Complete traceback

```
Traceback (most recent call last):
  File "/Users/princeduepa/Documents/sage-management-apis/app.py", line 11, in <module>
    from flask_uploads import configure_uploads, UploadSet, DATA
  File "/Users/princeduepa/Documents/sage-management-apis/venv/lib/python3.7/site-packages/flask_uploads.py", line 26, in <module>
    from werkzeug import secure_filename, FileStorage
ImportError: cannot import name 'secure_filename' from 'werkzeug' (/Users/princeduepa/Documents/sage-management-apis/venv/lib/python3.7/site-packages/werkzeug/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/princeduepa/Documents/sage-management-apis/venv/lib/python3.7/site-packages/flask/cli.py", line 338, in __call__
    self._flush_bg_loading_exception()
  File "/Users/princeduepa/Documents/sage-management-apis/venv/lib/python3.7/site-packages/flask/cli.py", line 326, in _flush_bg_loading_exception
    reraise(*exc_info)
  File "/Users/princeduepa/Documents/sage-management-apis/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/princeduepa/Documents/sage-management-apis/venv/lib/python3.7/site-packages/flask/cli.py", line 314, in _load_app
    self._load_unlocked()
  File "/Users/princeduepa/Documents/sage-management-apis/venv/lib/python3.7/site-packages/flask/cli.py", line 330, in _load_unlocked
    self._app = rv = self.loader()
  File "/Users/princeduepa/Documents/sage-management-apis/venv/lib/python3.7/site-packages/flask/cli.py", line 392, in load_app
    app = locate_app(self, import_name, None, raise_if_not_found=False)
  File "/Users/princeduepa/Documents/sage-management-apis/venv/lib/python3.7/site-packages/flask/cli.py", line 247, in locate_app
    "\n\n{tb}".format(name=module_name, tb=traceback.format_exc())
flask.cli.NoAppException: While importing "app", an ImportError was raised:

Traceback (most recent call last):
  File "/Users/princeduepa/Documents/sage-management-apis/venv/lib/python3.7/site-packages/flask/cli.py", line 240, in locate_app
    __import__(module_name)
  File "/Users/princeduepa/Documents/sage-management-apis/app.py", line 11, in <module>
    from flask_uploads import configure_uploads, UploadSet, DATA
  File "/Users/princeduepa/Documents/sage-management-apis/venv/lib/python3.7/site-packages/flask_uploads.py", line 26, in <module>
    from werkzeug import secure_filename, FileStorage
ImportError: cannot import name 'secure_filename' from 'werkzeug' (/Users/princeduepa/Documents/sage-management-apis/venv/lib/python3.7/site-packages/werkzeug/__init__.py)
```

Relevant `requirements.txt`

```
Flask==1.1.2
Flask-Uploads==0.2.1
Werkzeug==1.0.1
```
## Before
```python
from flask_uploads import configure_uploads, UploadSet, DATA
csv_upload = UploadSet(DATA)
.
.
.
app = create_app()
# Flask_Uploads
app.config.update(UPLOADED_FILES_DEST=path.join(app.instance_path, 'uploads'))
configure_uploads(app=app, upload_sets=csv_upload)
```
## After
```python
app = create_app()

# Flask_Uploads
from flask_uploads import configure_uploads, UploadSet, DATA

csv_upload = UploadSet(DATA)
app.config.update(UPLOADED_FILES_DEST=path.join(app.instance_path, 'uploads'))
configure_uploads(app=app, upload_sets=csv_upload)

**Comment by jugmac00** [comment]
The above error message was generated, as `Werkzeug`, a very important library in the Flask ecosystem, changed its API in version 1.0, back in February 2020.

This broke a lot of plugins.

I provided a pull request to this repository, see #28.

This pull request was merged, but @maxcountryman chose not to release a new version to PyPi. I even offered my help.

You can read his argument here:
https://github.com/maxcountryman/flask-uploads/issues/29#issuecomment-614218327

The latest version on PyPi (0.2.1) is from 2016, and you cannot use it with the latest versions of e.g. Werkzeug.

You certainly could pin `Flask-Uploads` to a GitHub commit id.

I think this is inconvenient at least, and doing so brought me a lot of problems, as this worked on my dev machine, but Travis CI was broken. So I really prefer to install from PyPi.

While I finally managed it, I felt a bit sad for all those developers asking here for help and a new release.

After now almost six months, there is still no new release.

I have thought about this situation a lot. On the one hand, the GitHub repository is kinda up to date (the test suite is broken, and some more... ), on the other hand there are many developers out there having trouble to fix their broken app.

So, yesterday I finally decided to fork this package, and after fixing the test suite and some more housekeeping, I released a new version to PyPi, most importantly with a fix to the broken `Werkzeug` import - and tons more.

As only the maintainer here has access to `Flask-Uploads` on PyPi, I created a new name: `Flask-Reuploaded`.

My main goal is to stay compatible with `Flask-Uploads` - it even is a drop-in replacement!

This means, instead of installing `Flask-Uploads` you only have to install `Flask-Reuploaded` and your migration work is finished. You do not have to change a single line of code.

The package is found here
https://pypi.org/project/Flask-Reuploaded/

And the repository is here
https://github.com/jugmac00/flask-reuploaded

Speaking of repository, while I have fixed the broken test suite, set up CI and more, there is still lots to do - especially beginner friendly tasks. If you ever wanted to contribute to open source, why not to the library you use?
https://github.com/jugmac00/flask-reuploaded/issues

When you now think.. huh, this one guy... why should I use his package? Maybe he is too busy soon, too?

The company I work for relies on `Flask-Reuploaded` - so there is big motivation to keep it working. Also, I love Python and open source, and I am super open for other contributors.

Even, my dream would be a `Flask Umbrella` organization, which the Flask plugin developers could join and share the work more evenly. See my proposal to the Pallets project here:
https://github.com/pallets/meta/issues/28

This all said - I am super thankful to Max and all the other contributors to this and other open source packages. I respect the decision not to release a package. The beauty of open source is choice. And now there is a choice, when you want a working PyPi package.

https://pypi.org/project/Flask-Reuploaded/

Thanks!

**Comment by maxcountryman** [comment]
You can use git to install any arbitrary revision. It’s pretty straightforward, altho may depend on your exact tooling. There’s been a lot of discussion about releases and this solution has been offered. Please use it.

I’m going to consider further requests for releases as off topic given the above.

I’m also going to close this since it’s not an issue with the existing codebase.
