### ISSUE TITLE
pip package of flask-uploads is not update

### ISSUE THREAD

**Issue by MohsenZanganeh** [maxcountryman/flask-uploads#57]
in this Repository of flask-uploads, in 26 line the `from werkzeug import secure_filename, FileStorage`
is updated to 
`from werkzeug.datastructures import FileStorage`
`from werkzeug.utils import secure_filename`

but when you download the `flask-uploads` from pip you don't get this update

when you create a docker container and the app is included this package your app in docker goes wrong and that container doesn't create

**please help me**

**Comment by born2discover** [comment]
Having stumbled upon this myself recently upon a legacy app migration, here's the issue:

- PyPI version 0.2.1 dates back to 2016
- Despite the fact that setup.py in the repository also displays the version of this package as being 0.2.1, several changes have been made to the codebase since. So technically the version is no longer 0.2.1.

If you really need to install it, I would suggest doing so directly from git, like so:

`pip install git+https://github.com/maxcountryman/flask-uploads.git#master` or
`poetry add git+https://github.com/maxcountryman/flask-uploads.git#master`

However, considering the lack of any meaningful activity and development, I wouldn't recommend using this package. At best, in its current state it could be used as inspiration.

**Comment by jugmac00** [comment]
@born2discover I have created a fork over at https://github.com/jugmac00/flask-reuploaded which has been in active development for two years now.

**Comment by born2discover** [comment]
@jugmac00 Wasn't aware of its existence. Thank you!

**Comment by MohsenZanganeh** [comment]
thanks for you all.
@jugmac00
@born2discover
